version: "3.9"  # optional since v1.27.0

services:
  dynamodb:
    image:  amazon/dynamodb-local:latest
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./.dynamodb-local-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"