# serverless.yml
org: cadesalaberry
app: api-swipe-me

service: api-swipe-me

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-webpack # should be before dynamodb and offline
  - serverless-finch # should be before dynamodb and offline
  - serverless-dynamodb-local
  - serverless-offline  # should be last in list
  - offline-invalidate # HACK: invalidate cache in dev to support serverless hot-reload

custom:
  client:
    bucketName: ${self:custom.computed.shortStageName}.swipeme.io
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: dev.swipeme.io
    stage: ${self:custom.stage}
    basePath: ${self:custom.stage}
    certificateName: dev.swipeme.io
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
  stage: ${opt:stage, 'dev'}
  computed: ${file(./packages/api/config.js)}
  cognito:
    identity-pool: swipeme_io_${self:custom.computed.snakedStage}_id_pool
    user-pool: swipeme.io-${self:custom.stage}-user-pool
    user-pool-client: swipeme.io-${self:custom.stage}-user-pool-client
    # https://swipeme-io-local.auth.eu-west-1.amazoncognito.com/
    user-pool-domain: swipeme-io-${self:custom.stage}
    # Defaults to 'http://localhost:8080/'
    user-pool-redirect-url: ${self:custom.computed.appDomainUrl}
    google-client-id: ${env:SWIPE_ME_SSO_GOOGLE_CLIENT_ID}
    google-client-secret: ${env:SWIPE_ME_SSO_GOOGLE_CLIENT_SECRET}
  tables:
    users: users-table-${self:custom.stage}
    decks: decks-table-${self:custom.stage}
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  dynamodb:
    start:
      migrate: true
      seed: true
    stages:
      - ${self:custom.stage}
    seed:
      development:
        sources:
          - table: ${self:custom.tables.users}
            sources: [./packages/api/seeds/users.json]
          - table: ${self:custom.tables.decks}
            sources: [./packages/api/seeds/decks.json]

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  iamRoleStatementsName:
    Fn::Join:
      - '-'
      - - ${self:service}
        - ${self:custom.computed.shortStageName}
        - ${self:provider.region}
        - 'lambdaRole'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["DecksDynamoDBTable", "Arn"] }

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_USER_POOL_ID: !Ref CognitoUserPool
    AWS_IDENTITY_POOL_ID: !Ref CognitoIdentityPool
    AWS_USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
    AWS_USER_POOL_DOMAIN: ${self:custom.cognito.user-pool-domain}
    AWS_USER_POOL_REDIRECT_URL: ${self:custom.cognito.user-pool-redirect-url}
    AWS_COGNITO_REGION: ${self:provider.region}
    AWS_S3_REGION: ${self:provider.region}
    AWS_S3_BUCKET: !Ref S3Bucket
    STAGE: ${self:custom.stage}
    USERS_TABLE: ${self:custom.tables.users}
    DECKS_TABLE: ${self:custom.tables.decks}
    DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
    NODE_ENV: ${env:NODE_ENV, 'production'}

functions:
  app:
    handler: packages/api/src/index.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /config.json
          method: GET
          cors: true
      - http:
          path: /decks
          method: POST
          cors: true
      - http:
          path: /decks
          method: GET
          cors: true
      - http:
          path: /decks/{deckHandle}
          method: GET
          cors: true

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-tables.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/cloudfront.yml)}
