# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  deploy_frontend:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: yarn
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn build
      - run: |
          if [ "$CIRCLE_BRANCH" = "master" ]; then
            yarn deploy
          fi

  deploy_backend:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "serverless/yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          working_directory: ~/project/serverless
          command: yarn
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "serverless/yarn.lock" }}
          paths:
            - serverless/node_modules
      - run:
          working_directory: ~/project/serverless
          command: |
            # if [ "$CIRCLE_BRANCH" = "master" ]; then
            yarn deploy
            #fi

# Orchestrate or schedule a set of jobs
workflows:
  deploy:
    jobs:
      - deploy_frontend
      - deploy_backend
