# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: yarn
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build
      - run: yarn api:lint
      - run: SLS_DEBUG=* yarn api:deploy
      - run: yarn client:lint
      - run: yarn client:build
      - run: yarn client:deploy

# Orchestrate or schedule a set of jobs
workflows:
  deploy:
    jobs:
      - deploy:
          context: dev.swipeme.io
