# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  deploy:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v4-{{ .Branch }}-
            - node-v4-
      - run: yarn
      - run: yarn build
      # needed to install brancher properly
      - run: yarn add ./packages/tools -W
      - run: ls -la node_modules/.bin
      - save_cache:
          key: node-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn brancher
      - run: yarn api:lint
      - run: SLS_DEBUG=* yarn api:deploy
      - run: yarn client:lint
      - run: yarn client:build
      - run: yarn client:deploy
  cypress:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v4-{{ .Branch }}-
            - node-v4-
      - run: yarn
      - run: yarn build
      # needed to install brancher properly
      - run: yarn add ./packages/tools -W
      # Install dynamodb for serverless-offline
      - run: yarn sls dynamodb install
      - run: ls -la node_modules/.bin
      - save_cache:
          key: node-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          command: SLS_DEBUG=* yarn api
          background: true


# Orchestrate or schedule a set of jobs
workflows:
  ci:
    jobs:
      - deploy:
          context: dev.swipeme.io
      - cypress:
          context: dev.swipeme.io
      - cypress/run:
          context: dev.swipeme.io
          executor: cypress/base-12
          yarn: true
