# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: cimg/node:14.18
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v4-{{ .Branch }}-
            - node-v4-
      - run: yarn
      - run: yarn build
      # needed to install brancher properly
      - run: yarn add file:packages/tools -W --frozen-lockfile --dev
      - run: ls -la node_modules/.bin
      - save_cache:
          key: node-v4-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/client/dist
            - .dynamodb

      - run: yarn brancher
      - run: yarn api:lint
      # - run: SLS_DEBUG=* yarn api:deploy
      - run: yarn client:lint
      - run: yarn client:build
      # - run: yarn client:deploy

# Orchestrate or schedule a set of jobs
workflows:
  ci:
    jobs:
      - build:
          context: dev.swipeme.io
      - cypress/install:
          context: dev.swipeme.io
          executor: cypress/base-14
          yarn: true
          install-command: |
            yarn install --ignore-engines
            yarn build
            yarn add file:packages/tools -W --ignore-engines --frozen-lockfile --dev
            yarn brancher
            yarn client:build
            yarn serverless dynamodb install
      - cypress/run:
          requires: [build, cypress/install]
          context: dev.swipeme.io
          executor: cypress/base-14
          yarn: true
          install-command: yarn install --ignore-engines
          start: yarn serve
          wait-on: http://localhost:3000
          command-prefix: yarn percy exec --
