Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    # Makes sure to delete the resource when the stack is deleted
    DeletionPolicy: Delete
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:custom.cognito.user-pool}
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    # Makes sure to delete the resource when the stack is deleted
    DeletionPolicy: Delete
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:custom.cognito.user-pool-client}
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
