Resources:
  DecksDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        -
          AttributeName: deckHandle
          AttributeType: S
      KeySchema:
        -
          AttributeName: deckHandle
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.tables.decks}
  SingleDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        -
          AttributeName: PK
          AttributeType: S
        -
          AttributeName: SK
          AttributeType: S
      KeySchema:
        -
          AttributeName: PK
          KeyType: HASH
        -
          AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.tables.single}