# serverless.yml
org: cadesalaberry
app: api-swipe-me

service: api-swipe-me

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-plugin-typescript # should be before dynamodb and offline
  - serverless-dynamodb-local
  - serverless-offline  # should be last in list

custom:
  stage: ${opt:stage, 'dev'}
  usersTableName: "users-table-${self:custom.stage}"
  decksTableName: "decks-table-${self:custom.stage}"
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  dynamodb:
    start:
      migrate: true
      seed: true
    stages:
      - ${self:custom.stage}
    seed:
      development:
        sources:
          - table: ${self:custom.usersTableName}
            sources: [./seeds/users.json]
          - table: ${self:custom.decksTableName}
            sources: [./seeds/decks.json]

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["DecksDynamoDBTable", "Arn"] }

  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    DECKS_TABLE: ${self:custom.decksTableName}
    DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-tables.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
