name: Cleanup stack once the branch is deleted

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
 
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Install dependencies
      run: yarn --frozen-lockfile

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
    - name: Cache Node.js modules
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn api:remove
